# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=200)),
                ('against', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.CreateModel(
            name='PPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_way', models.CharField(choices=[(b'F', b'Fast'), (b'I', b'Isolation'), (b'OS', b'Off-ball Screen'), (b'DK', b'Driving Kick'), (b'C', b'Cut'), (b'O', b'Other'), (b'PNR', b'Pick and Roll'), (b'S', b'Second'), (b'PU', b'Post Up'), (b'HU', b'High Post')], default=b'', max_length=3)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdag.Game')),
            ],
        ),
    ]
