# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppp',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='PPP',
        ),
    ]
