# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0003_auto_20170414_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='deflections',
        ),
        migrations.RemoveField(
            model_name='defense',
            name='total',
        ),
    ]
