# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0004_auto_20170414_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defense',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vdag.Player'),
        ),
    ]
