# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0005_ppp_shot_way'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ppp',
            unique_together=set([('game', 'offense_way', 'shot_way')]),
        ),
    ]
