# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0008_game_against'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vdag.Game')),
            ],
        ),
    ]
