# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0009_turnover'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnover',
            name='badpass',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnover',
            name='charging',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnover',
            name='drop',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnover',
            name='line',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnover',
            name='stolen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnover',
            name='team',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnover',
            name='three_second',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turnover',
            name='traveling',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
