# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0009_auto_20170508_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boxscore',
            unique_together=set([('game', 'isTeamBoxScore', 'player', 'quarter')]),
        ),
    ]
