# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0010_auto_20170412_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShotChart',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vdag.Game')),
                ('zone1_made', models.PositiveSmallIntegerField(default=0)),
                ('zone1_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone1_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone2_made', models.PositiveSmallIntegerField(default=0)),
                ('zone2_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone2_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone3_made', models.PositiveSmallIntegerField(default=0)),
                ('zone3_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone3_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone4_made', models.PositiveSmallIntegerField(default=0)),
                ('zone4_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone4_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone5_made', models.PositiveSmallIntegerField(default=0)),
                ('zone5_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone5_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone6_made', models.PositiveSmallIntegerField(default=0)),
                ('zone6_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone6_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone7_made', models.PositiveSmallIntegerField(default=0)),
                ('zone7_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone7_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone8_made', models.PositiveSmallIntegerField(default=0)),
                ('zone8_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone8_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone9_made', models.PositiveSmallIntegerField(default=0)),
                ('zone9_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone9_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone10_made', models.PositiveSmallIntegerField(default=0)),
                ('zone10_attempt', models.PositiveSmallIntegerField(default=0)),
                ('zone10_hit_rate', models.PositiveSmallIntegerField(default=0)),
                ('zone11_made', models.PositiveSmallIntegerField(default=0)),
                ('zone11_attempt', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
