# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0010_auto_20170508_1036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ppp',
            unique_together=set([('game', 'offense_way', 'shot_way', 'result', 'player', 'isTeamPPP')]),
        ),
    ]
