# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0013_timeline_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=200)),
                ('height', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=0)),
                ('used_hand', models.CharField(choices=[(b'L', b'Left hand'), (b'R', b'Right hand')], default=b'R', max_length=1)),
            ],
        ),
    ]
