# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0014_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='player_get_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdag.Player'),
        ),
    ]
