# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0015_timeline_player_get_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='player_get_on',
        ),
        migrations.AddField(
            model_name='timeline',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vdag.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveSmallIntegerField(default=175),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveSmallIntegerField(default=70),
        ),
    ]
