# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0016_auto_20170412_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='vdag.Player'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='vdag.Player'),
        ),
    ]
