# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0017_auto_20170412_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='bonus_attempt',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='bonus_made',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='offense_way',
            field=models.CharField(choices=[(b'F', b'Fast'), (b'I', b'Isolation'), (b'OS', b'Off-ball Screen'), (b'DK', b'Driving Kick'), (b'C', b'Cut'), (b'O', b'Other'), (b'PNR', b'Pick and Roll'), (b'S', b'Second'), (b'PU', b'Post Up'), (b'HU', b'High Post')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='vdag.Player'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='player3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='vdag.Player'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='player4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='vdag.Player'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='player5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='vdag.Player'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='player_get_off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_get_off', to='vdag.Player'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='player_get_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_get_on', to='vdag.Player'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='result',
            field=models.CharField(blank=True, choices=[(b'M', b'Made'), (b'A', b'Attempt'), (b'F', b'Foul')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='shot_way',
            field=models.CharField(choices=[(b'D', b'Drive'), (b'PU', b'Pull Up'), (b'SU', b'Spot Up'), (b'TO', b'Turnover')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='time_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeline',
            name='time_sec',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
