# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0018_auto_20170412_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='substitute',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='offense_way',
            field=models.CharField(blank=True, choices=[(b'F', b'Fast'), (b'I', b'Isolation'), (b'OS', b'Off-ball Screen'), (b'DK', b'Driving Kick'), (b'C', b'Cut'), (b'O', b'Other'), (b'PNR', b'Pick and Roll'), (b'S', b'Second'), (b'PU', b'Post Up'), (b'HU', b'High Post')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='vdag.Player'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='player_get_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_get_off', to='vdag.Player'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='player_get_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_get_on', to='vdag.Player'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='result',
            field=models.CharField(blank=True, choices=[(b'M', b'Made'), (b'A', b'Attempt'), (b'F', b'Foul'), (b'N1', b'And One')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='shot_way',
            field=models.CharField(blank=True, choices=[(b'D', b'Drive'), (b'PU', b'Pull Up'), (b'SU', b'Spot Up'), (b'TO', b'Turnover')], max_length=2, null=True),
        ),
    ]
