# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 08:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0019_auto_20170412_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='quarter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
