# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdag', '0021_auto_20170412_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='bonus_attempt',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='bonus_made',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
